dhcp-stats: dhcp-stats.py
			cp dhcp-stats.py dhcp-stats
			chmod +x dhcp-stats
			rpm -qa | egrep -q epel-release || sudo yum install epel-release
			rpm -qa | egrep -q pcapy || sudo yum install pcapy